# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: ignore
module Rack::QueryParser::InvalidParameterError; end
module Rack::QueryParser::ParameterTypeError; end
module Rack::QueryParser::Params; end
module Zip::CompressionMethodError; end
module Zip::DestinationFileExistsError; end
module Zip::EntryExistsError; end
module Zip::EntryNameError; end
module Zip::Error; end
module Zip::InternalError; end
